# Generated by Django 3.1.1 on 2020-12-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomments', '0002_auto_20201208_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refoodcomment',
            old_name='comment',
            new_name='foodcomment',
        ),
    ]
