# Generated by Django 3.1.1 on 2020-12-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomments', '0003_auto_20201208_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='refoodcomment',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refoodcomment',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
