# Generated by Django 3.1.1 on 2020-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomments', '0004_auto_20201208_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='refoodcomment',
            name='is_down_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='refoodcomment',
            name='is_up_list',
            field=models.TextField(default=''),
        ),
    ]
