# Generated by Django 3.1.1 on 2021-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutdata', '0003_nutdata_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_0',
            name='NUTR_CONT9',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='NUTR_CONT9',
            field=models.CharField(default='', max_length=50),
        ),
    ]
