# Generated by Django 3.1.1 on 2021-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutdata', '0005_auto_20210315_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='FOOD_CD',
            new_name='CALORIES',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='NUTR_CONT1',
            new_name='CHOLESTEROL',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='DESC_KOR',
            new_name='FOOD_CLASS',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='GROUP_NAME',
            new_name='FOOD_GROUP',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='NUTR_CONT2',
            new_name='NATRIUM',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='SAMPLING_MONTH_NAME',
            new_name='PROD_NAME',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='NUTR_CONT3',
            new_name='PROTEIN',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='SAMPLING_REGION_NAME',
            new_name='REFERENCE',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='NUTR_CONT4',
            new_name='SATURATED_FAT',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='NUTR_CONT5',
            new_name='SUGAR',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='NUTR_CONT6',
            new_name='TOTAL_CARB',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='NUTR_CONT7',
            new_name='TOTAL_FAT',
        ),
        migrations.RenameField(
            model_name='nutdata_1',
            old_name='NUTR_CONT8',
            new_name='TRANS_FAT',
        ),
        migrations.RemoveField(
            model_name='nutdata_1',
            name='NUTR_CONT9',
        ),
        migrations.RemoveField(
            model_name='nutdata_1',
            name='SAMPLING_MONTH_CD',
        ),
        migrations.RemoveField(
            model_name='nutdata_1',
            name='SAMPLING_REGION_CD',
        ),
        migrations.RemoveField(
            model_name='nutdata_1',
            name='SERVING_SIZE',
        ),
        migrations.RemoveField(
            model_name='nutdata_1',
            name='SUB_REF_NAME',
        ),
        migrations.AddField(
            model_name='nutdata_1',
            name='SERV_SIZE',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='RESEARCH_YEAR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutdata_1',
            name='UNIT',
            field=models.CharField(default='g', max_length=10),
        ),
    ]
