# Generated by Django 3.1.1 on 2020-12-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcomments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcomment',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
