# Generated by Django 3.1.1 on 2021-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoPushToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expotoken', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=50)),
            ],
        ),
    ]
