# Generated by Django 3.1.1 on 2021-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotificationdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_users', models.CharField(default='NO', max_length=50)),
                ('message', models.CharField(default='NO', max_length=500)),
                ('title', models.CharField(default='NO', max_length=200)),
            ],
        ),
    ]
